### PR TITLE
添加按钮，方便移动设备

### PR DESCRIPTION
**Pull request by ChinaGodMan**
@adamlui ❤️   #44
老美兄弟，添加了一个按钮用于在移动设备上
:trollface: 我在手机上就不用滑到最后了，希望你能同意这次合并请求

### CODE REVIEW

**Review by adamlui — APPROVED** [review]

**Comment by adamlui** [comment]
thanks @ChinaGodMan, btw for multi-type changes it's better to open multi-PRs so easier to review code for specific change, e.g. one for space changes one for add `insertBtn()`

**Comment by ChinaGodMan** [comment]
> thanks @ChinaGodMan, btw for multi-type changes it's better to open multi-PRs so easier to review code for specific change, e.g. one for space changes one for add `insertBtn()`

为什么打开多个PR？这是什么高端技术吗？

**Comment by adamlui** [comment]
@ChinaGodMan because I didn't want the space changes (since I do Find/Replace ALL across all my scripts for shared functions, now they are not identical) but I want you to have the button so it forced me to merge the unwanted space changes

**Comment by adamlui** [comment]
@ChinaGodMan and it doesn't matter if something is high-end tech or not, across all of GitHub PRs are one topic per PR for this reason, I don't know why you are attacking my code with insults like I made you mad when it is for your benefit to know this  common practice on GitHub

**Comment by ChinaGodMan** [comment]
> @ChinaGodMan because I didn't want the space changes (since I do Find/Replace ALL across all my scripts for shared functions, now they are not identical) but I want you to have the button so it forced me to merge the unwanted space changes@ChinaGodMan

啥意思？这个按钮代码插入进去破坏了你原来的代码结构？

**Comment by adamlui** [comment]
Your PR said "add button" but it was misleading, you changed dozens of lines with whitespace changes, so when I do mass edits to all my userscripts, it will no longer update this one, also when contributing to open source projects typically it stays in the style of the author, for example if I edit your scripts and made them all 16-space indents, would you change them back or not? If I opened a PR for that you would just close it. But if I added a feature and added 16-space indents everywhere, what would you do to that PR?

**Comment by ChinaGodMan** [comment]
@adamlui 是因为我vscode Format之后的代码和你的不相同嘛？我似乎看到了，代码保存后格式化了。是这个原因吗？老铁

**Comment by adamlui** [comment]
> @adamlui 是因为我vscode Format之后的代码和你的不相同嘛？我似乎看到了，代码保存后格式化了。是这个原因吗？老铁 @adamlui Is it because the code after my vscode Format is different from yours? I seem to see that the code is formatted after saving. Is this the reason? old man

I don't know the reason only you do, I cannot time travel and put my eyes in your head. Also this is a great lesson to examine diff before submitting PRs anywhere, to ensure your change truly matches your title or else it is like you tricked people. Also you are almost 30 did you know you are not a little boy anymore?

**Comment by adamlui** [comment]
You learn many valuable lessons from wise old men you are so lucky

**Comment by ChinaGodMan** [comment]
> Your PR said "add button" but it was misleading, you changed dozens of lines with whitespace changes, so when I do mass edits to all my userscripts, it will no longer update this one, also when contributing to open source projects typically it stays in the style of the author, for example if I edit your scripts and made them all 16-space indents, would you change them back or not? If I opened a PR for that you would just close it. But if I added a feature and added 16-space indents everywhere, what would you do to that PR?

我这个缩进是多少个空格？我不知道。我只是一个小白😳

**Comment by adamlui** [comment]
That was just example, your whtiespace changes included deletions too. But the final lesson is, examine diff before submitting PR and you will grow powerful from habit so less errors occur

**Comment by ChinaGodMan** [comment]
> You learn many valuable lessons from wise old men you are so lucky

❤️谢谢你，你真是个美国好人
 我不知道怎么在vscode编辑代码时如何保持和原来作者代码的风格一样，也许下次PR时我直接从Github编辑代码

**Comment by adamlui** [comment]
I think you copied/pasted then, that is when VSCode is very naughty. If you clone/fork instead, then open file, it behaves like good boy

**Comment by ChinaGodMan** [comment]
> I think you copied/pasted then, that is when VSCode is very naughty. If you clone/fork instead, then open file, it behaves like good boy

我是克隆仓库下载到本地之后，把暴力猴里面的已经测试好的代码复制到克隆后的脚本内的。😅 你说了这个问题之后我刚刚看了一下我另外PR的仓库，那个作者已经把他的仓库存档只读了

**Comment by adamlui** [comment]
What repository is archive read-only?

**Comment by adamlui** [comment]
A repository you opened PR in that also destroyed style so you suspect maintainer archived because of you?

**Comment by ChinaGodMan** [comment]
> A repository you opened PR in that also destroyed style so you suspect maintainer archived because of you?

破坏什么？也没有合并怎么会破坏呢。孩子

**Comment by adamlui** [comment]
> > A repository you opened PR in that also destroyed style so you suspect maintainer archived because of you?
> 
> 破坏什么？也没有合并怎么会破坏呢。孩子 Destroy what? How can it be destroyed without merging. child

I don't know, I'm asking because translation is weak. What repository is archived, just link it I shall investigate myself

**Comment by adamlui** [comment]
Do you wish to be a father? You speak of child often I notiecd

**Comment by ChinaGodMan** [comment]
> > > A repository you opened PR in that also destroyed style so you suspect maintainer archived because of you?
> > 
> > 
> > 破坏什么？也没有合并怎么会破坏呢。孩子 Destroy what? How can it be destroyed without merging. child
> 
> I don't know, I'm asking because translation is weak. What repository is archived, just link it I shall investigate mys

> > > A repository you opened PR in that also destroyed style so you suspect maintainer archived because of you?
> > 
> > 
> > 破坏什么？也没有合并怎么会破坏呢。孩子 Destroy what? How can it be destroyed without merging. child
> 
> I don't know, I'm asking because translation is weak. What repository is archived, just link it I shall investigate myself我不知道，我问是因为翻译很弱。存档了什么存储库，只需链接它我会自己调查

哦，能翻译就不错了。要感谢科技

**Comment by adamlui** [comment]
> 
> 哦，能翻译就不错了。要感谢科技 Oh, it would be nice to be able to translate. Thanks to technology

We are both using Immersive Translate it seems. Today I found out it is banned from Greasy Fork. Do you know what happened? Are we using spyware?

**Comment by ChinaGodMan** [comment]
> > 哦，能翻译就不错了。要感谢科技 Oh, it would be nice to be able to translate. Thanks to technology
> 
> We are both using Immersive Translate it seems. Today I found out it is banned from Greasy Fork. Do you know what happened? Are we using spyware?看来我们都在使用沉浸式翻译。今天我发现它被 Greasy Fork 禁止了。你知道发生了什么事吗？我们使用间谍软件吗？

我使用的是[翻译机](https://greasyfork.org/zh-CN/scripts/378277) 
你说的那个脚本是因为里面有压缩代码。无法从greasyfork网站安装了。他们有自己的网站发布页面。
我在用你的`eslint-on-push-pr.yml` ，这个能检查代码的风格和错误。真不错 🤩

**Comment by adamlui** [comment]
You can also make the check pre-commit if you `npm i husky` then `npx husky init`, then replace .husky/pre-commit with my version which will `npm run lint` before each commit (also add my `lint` script from package.json to make it work). It is slow if project is large though, so you can `git commit -n` to skip pre-commit hooks, then the lint will occur online from GitHub Action instead

**Comment by ChinaGodMan** [comment]
> You can also make the check pre-commit if you `npm i husky -D` then `npx husky init`, then replace `.husky/pre-commit` script with my version, which will `npm run lint` before each commit (also add my `lint` script from `package.json` to make it work, also delete `test` script auto-added to `package.json` upon the `npx husky init` since it is not needed)如果您 npm i husky -D 然后 npx husky init，您还可以进行检查预提交，然后用我的版本替换 .husky/pre-commit 脚本，这将在每次提交之前 npm 运行 lint （还可以从包中添加我的 lint 脚本 .json 以使其正常工作，还要删除在 npx husky init 上自动添加到 package.json 的测试脚本，因为不需要）
> 
> It is slow if project is large though, so you can `git 提交 -n` to skip pre-commit hooks, then the lint will only occur online from `eslint-on-push-pr.yml` instead如果项目很大，速度会很慢，因此您可以 git commit -n 跳过预提交挂钩，然后 lint 只会从 eslint-on-push-pr.yml 在线发生

哦，本地提交之前检查不如在线检查。我很少使用npm。在线检查足矣 比如我仓库翻译脚本在本地运行因为谷歌在中国是无法使用的，在本地运行经常出现401 但是放在github运行啥问题也没有，翻译访问速度也快⭐

**Pull request merged**
